"""DocumentBuilder — converts a ProcessDefinition into structured documentation.

Produces the table format from the process documentation methodology:
  | Étape | Action | Outil | Décision | Irritant |

Output formats:
- Markdown (default)
- JSON (machine-readable, for KFabric ingestion)

The builder is deterministic and stateless — given the same ProcessDefinition,
it always produces the same output.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from jean.models import ProcessDefinition, ProcessStep


@dataclass
class DocumentRow:
    """One row in the process documentation table."""
    sequence: int
    action: str
    tool: str
    decision: str
    irritant_score: float
    related_event_types: list[str]


class DocumentBuilder:
    """Builds process documentation from a validated ProcessDefinition.

    Args:
        irritant_label_threshold: irritant_score above this → labeled as irritant in the table.
    """

    def __init__(self, irritant_label_threshold: float = 0.3) -> None:
        self.irritant_label_threshold = irritant_label_threshold

    def _step_to_row(self, step: ProcessStep) -> DocumentRow:
        return DocumentRow(
            sequence=step.sequence,
            action=step.action,
            tool=step.tool,
            decision=step.decision or "—",
            irritant_score=step.irritant_score,
            related_event_types=step.related_event_types,
        )

    def _irritant_label(self, score: float) -> str:
        if score >= 0.7:
            return "⚠ high"
        if score >= self.irritant_label_threshold:
            return "~ medium"
        return ""

    def to_markdown(self, process: ProcessDefinition) -> str:
        """Generate a Markdown document from the ProcessDefinition."""
        lines: list[str] = []

        # Header
        lines.append(f"# {process.name}")
        lines.append(f"\n**Version:** {process.version}  ")
        lines.append(f"**Context:** `{process.process_context}`  ")
        lines.append(f"**State:** {process.state.value}  ")
        if process.description:
            lines.append(f"\n{process.description}")

        # Trigger
        lines.append(f"\n## Trigger\n\n{process.trigger}")

        # Inputs / Outputs
        if process.inputs:
            lines.append("\n## Inputs\n")
            for inp in process.inputs:
                req = " *(required)*" if inp.required else " *(optional)*"
                lines.append(f"- **{inp.name}** — source: `{inp.source}`{req}")

        if process.outputs:
            lines.append("\n## Outputs\n")
            for out in process.outputs:
                lines.append(f"- **{out.name}** — destination: `{out.destination}`")

        # Steps table
        if process.steps:
            lines.append("\n## Steps\n")
            lines.append("| Étape | Action | Outil | Décision | Irritant |")
            lines.append("|-------|--------|-------|----------|----------|")
            for step in process.steps:
                row = self._step_to_row(step)
                irritant_cell = self._irritant_label(row.irritant_score)
                lines.append(
                    f"| {row.sequence} "
                    f"| {row.action} "
                    f"| {row.tool} "
                    f"| {row.decision} "
                    f"| {irritant_cell} |"
                )

        lines.append(f"\n---\n*Generated by Jean v1.0 — process-documentation*")
        return "\n".join(lines)

    def to_json(self, process: ProcessDefinition) -> dict:
        """Generate a machine-readable JSON dict from the ProcessDefinition."""
        rows = [self._step_to_row(s) for s in process.steps]
        return {
            "process_id": process.id,
            "name": process.name,
            "version": process.version,
            "process_context": process.process_context,
            "trigger": process.trigger,
            "inputs": [i.model_dump() for i in process.inputs],
            "outputs": [o.model_dump() for o in process.outputs],
            "steps": [
                {
                    "sequence": r.sequence,
                    "action": r.action,
                    "tool": r.tool,
                    "decision": r.decision,
                    "irritant_score": r.irritant_score,
                    "event_types": r.related_event_types,
                }
                for r in rows
            ],
            "generated_by": "jean-doc-generator",
            "schema_version": "1.0",
        }
